name: facedetection
channels:
  - conda-forge
  - pytorch
dependencies:
  - imgaug=0.4.0
  - numpy=1.19
  - opencv=4.4
  - pillow=8.0
  - py-opencv=4.4
  - python=3.6
  - pytorch=1.5
  - torchvision=0.8
  - wandb=0.10